package deeptibhatia.euler

import deeptibhatia.math.Fibonacci

/*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
object Project02 {

  def sumFibonacciLessThanLimit(limit: Int) = {
    lazy val fib = Fibonacci.fibonacciStream
    lazy val evenFib = fib.filter(x => (x %2 == 0))
    lazy val fibLessThanLimit = evenFib.takeWhile(_ < limit)

    fibLessThanLimit.foldLeft(0L)(_+_)
  }


}
